// Current User
export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_FULFILLED = 'LOG_OUT_FULFILLED';
export const LOG_IN = 'LOG_IN';
export const LOG_IN_FULFILLED = 'LOG_IN_FULFILLED';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FULFILLED = 'SIGN_UP_FULFILLED';
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_FULFILLED = 'FETCH_CURRENT_USER_FULFILLED';
// Publisher and admin types
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_FULFILLED  = 'FETCH_PROFILE_FULFILLED ';
export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_PROFILES_FULFILLED  = 'FETCH_PROFILES_FULFILLED ';

export const CREATE_PROFILE = 'CREATE_PROFILE';
export const CREATE_PROFILE_FULFILLED  = 'CREATE_PROFILE_FULFILLED ';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_FULFILLED  = 'UPDATE_PROFILE_FULFILLED ';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const DELETE_PROFILE_FULFILLED  = 'DELETE_PROFILE_FULFILLED ';
