// ------------------------- AUTH ------------------------------------------ //
export const USER_REQUEST = 'USER_REQUEST';
export const USER_RECEIVED = 'USER_RECEIVED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const RESET_LOGIN_STATUS = 'RESET_LOGIN_STATUS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const RESET_REGISTRATION_STATUS = 'RESET_REGISTRATION_STATUS';

// ------------------------- PROFILES -------------------------------------- //
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_FULFILLED  = 'FETCH_PROFILE_FULFILLED';
export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_PROFILES_FULFILLED  = 'FETCH_PROFILES_FULFILLED';

export const CREATE_PROFILE = 'CREATE_PROFILE';
export const CREATE_PROFILE_FULFILLED  = 'CREATE_PROFILE_FULFILLED';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_FULFILLED  = 'UPDATE_PROFILE_FULFILLED';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const DELETE_PROFILE_FULFILLED  = 'DELETE_PROFILE_FULFILLED';
export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const SET_CURRENT_PROFILE_FULFILLED  = 'SET_CURRENT_PROFILE_FULFILLED';
