// ------------------------- AUTH ------------------------------------------ //
export const USER_REQUEST = 'USER_REQUEST';
export const USER_RECEIVED = 'USER_RECEIVED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const RESET_LOGIN_STATUS = 'RESET_LOGIN_STATUS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const RESET_REGISTRATION_STATUS = 'RESET_REGISTRATION_STATUS';

// ------------------------- PROFILES -------------------------------------- //
export const PROFILES_REQUEST = 'PROFILES_REQUEST';
export const LOAD_PROFILES_SUCCESS = 'LOAD_PROFILES_SUCCESS';
export const LOAD_PROFILES_FAILURE = 'LOAD_PROFILES_FAILURE';
export const ADD_PROFILE_REQUEST = 'ADD_PROFILE_REQUEST';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_FAILURE = 'ADD_PROFILE_FAILURE';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const DELETE_PROFILE_REQUEST = 'DELETE_PROFILE_REQUEST';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';
export const DELETE_PROFILE_FAILURE = 'DELETE_PROFILE_FAILURE';
export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE';

// ------------------------- PROVIDERS ------------------------------------ //
export const PROVIDERS_REQUEST = 'PROVIDERS_REQUEST';
export const LOAD_PROVIDERS_SUCCESS = 'LOAD_PROVIDERS_SUCCESS';
export const LOAD_PROVIDERS_FAILURE = 'LOAD_PROVIDERS_FAILURE';
export const LINK_PROVIDER_REQUEST = 'LINK_PROVIDER_REQUEST';
export const LINK_PROVIDER_SUCCESS = 'LINK_PROVIDER_SUCCESS';
export const LINK_PROVIDER_FAILURE = 'LINK_PROVIDER_FAILURE';
export const OAUTH_CALLBACK_REQUEST = 'OAUTH_CALLBACK_REQUEST';
export const OAUTH_CALLBACK_SUCCESS = 'OAUTH_CALLBACK_SUCCESS';
export const OAUTH_CALLBACK_FAILURE = 'OAUTH_CALLBACK_FAILURE';

// ------------------------PROFILE PROVIDERS ---------------------------------//
export const PROFILE_PROVIDERS_REQUEST = 'PROFILE_PROVIDERS_REQUEST';
export const LOAD_PROFILE_PROVIDERS_SUCCESS = 'LOAD_PROFILE_PROVIDERS_SUCCESS';
export const LOAD_PROFILE_PROVIDERS_FAILURE = 'LOAD_PROFILE_PROVIDERS_FAILURE';
export const DELETE_PROFILE_PROVIDER_REQUEST = 'DELETE_PROFILE_PROVIDER_REQUEST';
export const DELETE_PROFILE_PROVIDER_SUCCESS = 'DELETE_PROFILE_PROVIDER_SUCCESS';
export const DELETE_PROFILE_PROVIDER_FAILURE = 'DELETE_PROFILE_PROVIDER_FAILURE';
// ------------------------- HEALTH RECORDS -------------------------------- //
export const HEALTH_RECORD_REQUEST = "HEALTH_RECORD_REQUEST";
export const LOAD_HEALTH_RECORD_SUCCESS = "LOAD_HEALTH_RECORD_SUCCESS";
export const LOAD_HEALTH_RECORD_FAILURE = "LOAD_HEALTH_RECORD_FAILURE";

export const RECEIVE_HEALTH_RECORD_PUSH_REQUEST = "RECEIVE_HEALTH_RECORD_PUSH_REQUEST";