import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAllergies,
  faCalendar,
  faCheck,
  faChevronDown,
  faChevronRight,
  faCircle,
  faEdit,
  faEllipsisH,
  faExclamationCircle,
  faFileMedicalAlt,
  faFlask,
  faHeartbeat,
  faHospital,
  faNotesMedical,
  faPills,
  faPlusCircle,
  faSignOutAlt,
  faSpinner,
  faSyringe,
  faUserCircle
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faAllergies,
  faCalendar,
  faCheck,
  faChevronDown,
  faChevronRight,
  faCircle,
  faEdit,
  faEllipsisH,
  faExclamationCircle,
  faFileMedicalAlt,
  faFlask,
  faHeartbeat,
  faHospital,
  faNotesMedical,
  faPills,
  faPlusCircle,
  faSignOutAlt,
  faSpinner,
  faSyringe,
  faUserCircle
);
